import { Navigation } from "../component/Navigation/Navigate";
import "../styles/globals.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<title>App the 🐈</title>
			</head>
			<body>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
